public without sharing class CreditApplicationContstants {
    
    public static final string Application_Status_Sent_To_Customer = 'Sent To Customer';
    public static final string Application_Status_Opened_To_Customer = 'Opened By Customer';
    public static final string Application_In_Progress = 'In Progress';
    public static final string Application_Status_Submitted = 'Submitted';
    public static final string Application_Status_In_Review = 'In Review';
    public static final string Application_Status_Submit_For_Approval = 'Submit For Approval';
    public static final string Application_Status_Approved = 'Approved';
	public static final string Application_Status_Rejected = 'Rejected';
    
    
    public static final string EmailTemplate_Credit_Application_Template = 'Credit_Application_Template';
    public static final string EmailTemplate_Rejected_For_End_User = 'Rejected_Email_Notification_For_End_User';
}