public class louisvilleTileConstants {
	
    public static final String LEAD_LINKS = 'Lead Links';
    public static final String OPPORTUNITY_LINKS = 'Opportunity Links';
    public static final String WON_OPPORTUNITY_LINKS = 'Won Opportunity Links';
    public static final String ORDER_LINKS = 'Order';
    public static final String Marketing = 'Marketing';
    public static final String oppYTD = 'All Opportunities in YTD';
    public static final String oppMTD = 'All Opportunities in MTD';
    public static final String accountInYTD = 'All Account in YTD';
    public static final String accountInMTD = 'All Account in MTD';
    public static final String contactYTD = 'All Contacts in YTD';
    public static final String contactMTD = 'All Contacts in MTD';
    public static final String leadYTD = 'All Lead in YTD';
    public static final String leadMTD = 'All Lead in MTD';
    public static final String designAndPlaning = 'Design and Planning';
    public static final String quoting = 'Quoting';
    public static final String postBidding = 'Post Bidding';
    public static final String contractorSubmittals = 'Contractor Submittals';
    public static final String onOrder = 'On Order';
    public static final String sold = 'Sold';
    public static final String closedLost = 'Closed Lost';
    public static final String opportunityRecordType = 'Commercial_Opportunities';
    
}