public without sharing class SampleRequestFormConstants {
    
    public static final String Form_Status_In_Progress = 'Save as Draft';
    public static final String Form_Status_Submitted = 'Submitted';
    public static final String Internal_SubmittedBy = 'Internal Employee';
    public static final String SubmittedBy_Decor24Users = 'External Users Decor24';
    public static final String SubmittedBy_Website = 'Website Enquiry';
   
}